name: Test Server Code

on:
  push:
    branches:
      - '**'
  pull_request:
    branches:
      - develop

jobs: 
  tests:
    runs-on: windows-latest

    steps:
      - name: Check out repo
        uses: actions/checkout@v3

      - name: Setup arduino-cli
        shell: pwsh
        run: |
          if (-not (Test-Path "C:\arduino-cli\arduino-cli.exe")) {
            Invoke-WebRequest -Uri "https://downloads.arduino.cc/arduino-cli/arduino-cli_latest_Windows_64bit.zip" -OutFile "arduino-cli.zip"
            Expand-Archive -Path "arduino-cli.zip" -DestinationPath "C:\arduino-cli"
          }
        
      - name: Setup ESP32 core
        shell: cmd
        run: |
          C:\arduino-cli\arduino-cli.exe config init
          C:\arduino-cli\arduino-cli.exe config set board_manager.additional_urls "https://raw.githubusercontent.com/espressif/arduino-esp32/gh-pages/package_esp32_index.json"
          C:\arduino-cli\arduino-cli.exe core update-index
          C:\arduino-cli\arduino-cli.exe core install esp32:esp32
        
      - name: Compile ESP32 Tests
        shell: cmd
        run: |
          C:\arduino-cli\arduino-cli.exe compile --fqbn esp32:esp32:esp32 test_server/test_server.ino

      - name: Run Unit Tests and Capture Output
        shell: cmd
          run: |
            C:\arduino-cli\arduino-cli.exe upload -p COM1 --fqbn esp32:esp32:esp32 test_server/test_code.ino > test_results.log 2>&1
  
      - name: Process Test Results
        shell: cmd
          run: |
            $testResults = Get-Content "test_results.log"
            
            if ($testResults -match "Test failed") {
              Write-Host "Tests failed!"
              exit 1  # Fail the workflow if tests failed
            } else {
              Write-Host "All tests passed!"
            }
  